setup.template.enabled: false

filebeat.inputs:
- type: filestream
  enabled: true
  close.reader.on_eof: true
  paths:
    - /var/log/liain/*.csv

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  # Protocol - either `http` (default) or `https`.
  protocol: "https"
  index: "liain"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "filebeat_user"
  password: "<some_filebeat_password_here>"
  ssl.verification_mode: "none"
  pipeline: "liain"
